# Generated by Django 2.0.6 on 2020-01-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roledetails',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
