# Generated by Django 2.0.6 on 2020-01-21 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roledetails',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='roledetails',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='roledetails',
            name='otp_time',
        ),
        migrations.RemoveField(
            model_name='roledetails',
            name='verify_link',
        ),
    ]
